### ISSUE TITLE
Alt+2 doesn't disable hitboxes.

### ISSUE THREAD

**Issue by Xcl4m4t10n** [maximusmaxy/JoJoban-Training-Mode-Menu-FBNeo#1]

**Comment by Xcl4m4t10n** [comment]
After posting it (like the second after) I noticed that it deactivates but doesn't clean the hitboxes.
![imagen](https://user-images.githubusercontent.com/35381298/97118068-54834b80-1708-11eb-8234-aa01d2105e46.png)

**Comment by maximusmaxy** [comment]
Thanks it will be fixed in the next release
